services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    

# Below is the command used to run the postgres image, environment variables referred from above image info
# docker run -it \
# -e POSTGRES_USER="root" \
# -e POSTGRES_PASSWORD="root" \
# -e POSTGRES_DB="ny_taxi" \
# -v "D:\Coding Stuff\Data Engineering\Data Engineering Zoomcamp\Docker_SQL\ny_taxi_postgres_data":/var/lib/postgresql/data:rw \
# -p "5432:5432" \
# --network=pg-network \
# --name pg-database \
# postgres:13

# Below is the command used to run the pgadmin image, environment variables referred from above image info
# docker run -it \
# -e PGADMIN_DEFAULT_EMAIL=admin@admin.com \
# -e PGADMIN_DEFAULT_PASSWORD=root \
# -p 8080:80 \
# --network=pg-network \
# --name pg-admin-test \
# dpage/pgadmin4

# Command to get both docker containers in same network (not required in docker-compose)
# docker network create pg-network

# URL to use in below commands
# URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"

# comand to run ingest_data file from command line (running the ingestion script using python command with new table name)
# python ingest_data.py \
# --user=root \
# --password=root \
# --host=localhost \
# --port=5432 \
# --db=ny_taxi \
# --table_name=yellow_taxi_trips \
# --url=${URL}

# Command used to build new image on ingestion script (above command)
# docker build -t taxi_ingest:v1 .

# command to run the ingestion script image using docker
# docker run -it \
# --network=pg-network \
# taxi_ingest:v1 \
# --user=root \
# --password=root \
# --host=pg-database \
# --port=5432 \
# --db=ny_taxi \
# --table_name=yellow_taxi_data \
# --url=${URL}


# command to run the ingestion script image using docker-compose
# docker run -it \
# --network=docker_sql_default \
# taxi_ingest:v1 \
# --user=root \
# --password=root \
# --host=pgdatabase \
# --port=5432 \
# --db=ny_taxi \
# --table_name=yellow_taxi_data \
# --url=${URL}

